import { ClerkProvider } from '@clerk/nextjs';
import Navbar from '@/components/navbar';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { QueryProvider } from '@/components/queryprovider';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Order Tracking',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <QueryProvider>
        <html lang='en'>
          <body className={inter.className}>
            <Navbar />
            {children}
          </body>
        </html>
      </QueryProvider>
    </ClerkProvider>
  );
}
